### ISSUE TITLE
Mobile width design changes

### ISSUE THREAD

**Issue by siruguri** [Hallm13/ideamapr#60]
# Participant

* Nav bar should switch to showing stage, instead of idea titles
* Budget details will stack and become 100%
* Idea card - image moves to top and is centered, and title/description stack beneath it
![iphone se - element widths](https://cloud.githubusercontent.com/assets/1813275/17345520/0f90a8e6-58cc-11e6-9977-22abd73cdc47.png)

# Admin

TBD

**Comment by Hallm13** [comment]
![iphone se - budget](https://cloud.githubusercontent.com/assets/1813275/17345094/1b198432-58ca-11e6-97a4-bebf117037e3.png)
![iphone se - idea detail](https://cloud.githubusercontent.com/assets/1813275/17345093/1b15a452-58ca-11e6-849f-64b1ac4a8f63.png)
![iphone se - ranking](https://cloud.githubusercontent.com/assets/1813275/17345095/1b1a2b76-58ca-11e6-948f-401544d604c1.png)

**Comment by Hallm13** [comment]
Font sizes are the same for mobile. The up/down ranking buttons are the same size. I'll keep finding elements and adjusting the sizes where necessary.

**Comment by siruguri** [comment]
I think the widths in the navbar are going to be challenging, even if we drop to 16px, leave alone 18px:

* If I make them all a third each (of 91%), then that'll be too narrow if the numbers in "X of Y" are not both <10. So I think "8 of 11" will exceed the space avlbl.
* If I make the middle one 50%, the word "Previous" won't fit in the left tab (which is now 25% rather than 33%)

So:

1. Change Previous/Next to arrows?
1. Drop font to 14px?

**Comment by Hallm13** [comment]
Can you try this out? 80px (25%) for the previous button, 80px (25%) for the next button, 80px (25%) for the dropdown, and 106px (33.125%) for the background between the next and previous buttons. This would make the overall width of the nav bar 87% instead of 91% but I think it would fit better.
![screen shot 2016-08-03 at 9 59 08 am](https://cloud.githubusercontent.com/assets/1813275/17370261/fd0eb3b2-5960-11e6-9e98-a722f02badb8.png)

**Comment by siruguri** [comment]
What font size are you using in the navbar mockups?
