### ISSUE TITLE
Ideas gathered via Idea gathering question should appear in the ideas list

### ISSUE THREAD

**Issue by Hallm13** [Hallm13/ideamapr#79]
While I realize that automatically adding participant ideas would make the idea list long, the point of the question type is to automatically add ideas. We could add a way to better manage the idea list to combat any issues with this feature.

**Comment by siruguri** [comment]
Yeah, let's nail down some simple way of separating "official" from "suggested" ideas, and I'll implement it.

**Comment by siruguri** [comment]
Show source on edit page:

* add source field for ideas
* add html on edit page

nothing changes on listings page.

**Comment by siruguri** [comment]
@Hallm13 - question for discussion tomorrow (8/5)

This is trickier than I thought. I could just extract the new ideas each time the list of ideas is shown - but to make them editable, they need to be converted into an editable representation, rather than just a reportable representation. But that will complicate the implementation of the Add Idea participant screen a lot, both now and for later. Let's discuss.

**Comment by siruguri** [comment]
For now we will implement towards admin control - edit and delete - of user-submitted ideas; ideas will appear to admins as soon as users submit them; users cannot delete their own ideas; admin deleted ideas will not affect reports.
